<html>
<body>
<style>
	table {
		border-spacing: 0;
		border-collapse: collapse;
	}
	table td, table th {
		border: 1px solid #ccc;
		padding: 5px;
	}
	table th {
		background: #eee;
	}
</style>
<h1>Здравствуйте, {{ login }}! Вот ваш список дел:</h1>
<p><a href="?/task/add/">Добавить задачу</a></p>
<div style="clear: both"></div>
<table>
	<tr>
		<th>Описание задачи</th>
		<th>Дата добавления</th>
		<th>Статус</th>
		<th></th>
		<th>Ответственный</th>
		<th>Автор</th>
		<th>Закрепить задачу за пользователем</th>
	</tr>
	{% for task in tasks %}
		{% if task.autor == login %}
	    <tr>
	        <td>{{ task.description }}</td>
	        <td>{{ task.date_added }}</td>
	        <td><span style='color: {% if task.is_done == 1 %} green;\'>Выполнено {% else %} red;\'>В процессе {% endif %}</span></td>
	        <td>
				<a href="?/task/edit/id/{{ task.id }}/">Изменить</a>
	            {% if task.assigned == null %}
					<a href="?/task/done/id/{{ task.id }}/">Выполнить</a>
	            {% endif %}
				<a href="?/task/delete/id/{{ task.id }}/">Удалить</a>
	        </td>
	        <td>{% if task.assigned == null %} Вы {% else %} {{ task.assigned }} {% endif %}</td>
	        <td>{{ task.autor }}</td>
	        <td>
	            <form method='POST'>
	            <select name='assigned_user_id'>
					{% for user in users %}
					{% if user.login != login %}
						<option value='user_{{ user.id }}_task_{{ task.id }}'>{{ user.login }}
					{% endif %}
					{% endfor %}
	                </option>
	            </select>
	            <input type='submit' name='assign' value='Переложить ответственность' />
	            </form>
	        </td>
	    </tr>
		{% endif %}
	{% endfor %}
</table>
<p><strong>Также, посмотрите, что от Вас требуют другие люди:</strong></p>
<table>
<tr>
	<th>Описание задачи</th>
	<th>Дата добавления</th>
	<th>Статус</th>
	<th></th>
	<th>Ответственный</th>
	<th>Автор</th>
</tr>
{% for task in tasks %}
	{% if task.assigned == login %}
	<tr>
		<td>{{ task.description }}</td>
		<td>{{ task.date_added }}</td>
		<td><span style='color: {% if task.is_done == 1 %} green;\'>Выполнено {% else %} red;\'>В процессе {% endif %}</span></td>
		<td>
			<a href="?/task/edit/id/{{ task.id }}/">Изменить</a>
			<a href="?/task/done/id/{{ task.id }}/">Выполнить</a>
			<a href="?/task/delete/id/{{ task.id }}/">Удалить</a>
		</td>
		<td>{{ task.assigned }}</td>
		<td>{{ task.autor }}</td>
	</tr>
	{% endif %}
{% endfor %}
</table>
</body>
</html>
